# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Added')),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Last time edited')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Name')),
                ('classname', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='classname')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional info')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Added')),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Last time edited')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (1, 'Skipped')], db_index=True, default=0)),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional info')),
                ('test_case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_history.TestCase', verbose_name='Test case')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Added')),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Last time edited')),
                ('job_url', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Job url')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestRunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Added')),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Last time edited')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Name')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Passed'), (1, 'Failed')], db_index=True, default=0)),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional info')),
                ('test_job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_history.TestJob', verbose_name='Test job')),
                ('test_results', models.ManyToManyField(blank=True, to='test_history.TestCaseResult', verbose_name='Test case results')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
