# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testjob',
            options={'ordering': ['job_name']},
        ),
        migrations.AddField(
            model_name='testjob',
            name='job_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Job name'),
        ),
    ]
