# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_history', '0002_auto_20170414_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='job_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='Job name'),
        ),
    ]
